name: Publish Packages

on:
   workflow_dispatch:

permissions:
   contents: read

jobs:
   build:
      runs-on: ubuntu-latest
      environment: nuget
      permissions:
         contents: write
         id-token: write

      steps:
         - uses: actions/checkout@v5
         - name: NuGet login
           uses: NuGet/login@v1
           id: login
           with:
             user: Glacor
         - name: Setup .NET
           uses: actions/setup-dotnet@v5
           with:
              dotnet-version: 11.0.x
         - name: Restore dependencies
           run: dotnet restore Transceiver.sln
         - name: Build
           run: dotnet build Transceiver.sln --configuration Release --no-restore
         - name: Test
           run: dotnet test Transceiver.sln --configuration Release --no-build --verbosity normal
         - parallel:
           - name: Publish Transceiver
             uses: alirezanet/publish-nuget@v3.1.0
             with:
                PROJECT_FILE_PATH: Transceiver/Transceiver.csproj
                VERSION_FILE_PATH: Directory.Build.props
                INCLUDE_SYMBOLS: true
                NUGET_KEY: ${{steps.login.outputs.NUGET_API_KEY}}
           - name: Publish Transceiver.Generator
             uses: alirezanet/publish-nuget@v3.1.0
             with:
                PROJECT_FILE_PATH: Transceiver.Generator/Transceiver.Generator.csproj
                VERSION_FILE_PATH: Directory.Build.props
                INCLUDE_SYMBOLS: true
                NUGET_KEY: ${{steps.login.outputs.NUGET_API_KEY}}
           - name: Publish Transceiver.AmazonSqs
             uses: alirezanet/publish-nuget@v3.1.0
             with:
                PROJECT_FILE_PATH: Transceiver.AmazonSqs/Transceiver.AmazonSqs.csproj
                VERSION_FILE_PATH: Directory.Build.props
                INCLUDE_SYMBOLS: true
                NUGET_KEY: ${{steps.login.outputs.NUGET_API_KEY}}
           - name: Publish Transceiver.AzureQueue
             uses: alirezanet/publish-nuget@v3.1.0
             with:
                PROJECT_FILE_PATH: Transceiver.AzureQueue/Transceiver.AzureQueue.csproj
                VERSION_FILE_PATH: Directory.Build.props
                INCLUDE_SYMBOLS: true
                NUGET_KEY: ${{steps.login.outputs.NUGET_API_KEY}}
           - name: Publish Transceiver.DomainSockets
             uses: alirezanet/publish-nuget@v3.1.0
             with:
                PROJECT_FILE_PATH: Transceiver.DomainSockets/Transceiver.DomainSockets.csproj
                VERSION_FILE_PATH: Directory.Build.props
                INCLUDE_SYMBOLS: true
                NUGET_KEY: ${{steps.login.outputs.NUGET_API_KEY}}
           - name: Publish Transceiver.GooglePubSub
             uses: alirezanet/publish-nuget@v3.1.0
             with:
                PROJECT_FILE_PATH: Transceiver.GooglePubSub/Transceiver.GooglePubSub.csproj
                VERSION_FILE_PATH: Directory.Build.props
                INCLUDE_SYMBOLS: true
                NUGET_KEY: ${{steps.login.outputs.NUGET_API_KEY}}
           - name: Publish Transceiver.Kafka
             uses: alirezanet/publish-nuget@v3.1.0
             with:
                PROJECT_FILE_PATH: Transceiver.Kafka/Transceiver.Kafka.csproj
                VERSION_FILE_PATH: Directory.Build.props
                INCLUDE_SYMBOLS: true
                NUGET_KEY: ${{steps.login.outputs.NUGET_API_KEY}}
           - name: Publish Transceiver.RabbitMq
             uses: alirezanet/publish-nuget@v3.1.0
             with:
                PROJECT_FILE_PATH: Transceiver.RabbitMq/Transceiver.RabbitMq.csproj
                VERSION_FILE_PATH: Directory.Build.props
                INCLUDE_SYMBOLS: true
                NUGET_KEY: ${{steps.login.outputs.NUGET_API_KEY}}
           - name: Publish Transceiver.ZeroMq
             uses: alirezanet/publish-nuget@v3.1.0
             with:
                PROJECT_FILE_PATH: Transceiver.ZeroMq/Transceiver.ZeroMq.csproj
                VERSION_FILE_PATH: Directory.Build.props
                INCLUDE_SYMBOLS: true
                NUGET_KEY: ${{steps.login.outputs.NUGET_API_KEY}}
           - name: Publish Transceiver.Websockets
             uses: alirezanet/publish-nuget@v3.1.0
             with:
                PROJECT_FILE_PATH: Transceiver.Websockets/Transceiver.Websockets.csproj
                VERSION_FILE_PATH: Directory.Build.props
                INCLUDE_SYMBOLS: true
                NUGET_KEY: ${{steps.login.outputs.NUGET_API_KEY}}
           - name: Publish Transceiver.Serializer.SerializerMessagePack
             uses: alirezanet/publish-nuget@v3.1.0
             with:
                PROJECT_FILE_PATH: Transceiver.Serializer.SerializerMessagePack/Transceiver.Serializer.SerializerMessagePack.csproj
                VERSION_FILE_PATH: Directory.Build.props
                INCLUDE_SYMBOLS: true
                NUGET_KEY: ${{steps.login.outputs.NUGET_API_KEY}}
